Update profile_view_page, add history_view_photos_page, refactor
zephxyz/Lifance pull request #7
Opened 2023-05-30 08:32 UTC by zephxyz

2023-05-31 16:01 UTC, Kerrely approved these changes

2023-05-31 16:01 UTC, Kerrely commented on lib/pages/history_view_page.dart
> +        ]));
Suggestion: zkus FAB (floatin action button) 😉

2023-06-07 16:28 UTC, Kerrely requested changes

2023-06-07 16:28 UTC, Kerrely commented on lib/pages/history_view_page.dart
> +    }
GridView nebo Wrap prosím 😄

2023-06-07 16:28 UTC, Kerrely commented on lib/pages/history_view_page.dart
> +      ),
Zvaž to s tou navigací a heroes 😉

2023-06-07 16:28 UTC, Kerrely commented on lib/pages/home_page.dart
>            }
Vzhledem k tomu, že sám nevíš co je `temp`... doporučuju pojmenovat tak aby bylo vidět co to dělá 😄

2023-06-07 16:28 UTC, Kerrely commented on lib/pages/home_page.dart
> +                    ? Text(displayDistance)
Nějak vizuálně vylepšit, přeci jen se dostáváme do nějakého toho finiše tak ať to i nějak vypadá 😉

2023-06-15 10:40 UTC, ZirixCZ commented on lib/pages/history_view_page.dart
> +      if(event == 1) {
Would it be possible to use enum instead of an int? for instance an enum that describes the event

2023-06-19 15:14 UTC, Kerrely approved these changes
Tak nějaké poslední komenty. Víceméně jsme se o všem bavili na callu a nějak si to shrnuli, tak si to po dokončení nějak mergni a good luck 😉

2023-06-19 15:14 UTC, Kerrely commented on lib/pages/profile_view_page.dart
> +  Future<void> deleteAccount() async {}
Zapomenuto :)

2023-06-19 15:14 UTC, Kerrely commented on lib/pages/profile_view_page.dart
>      goToLoginPage();
Zapomenuto 😉

2023-06-19 15:14 UTC, Kerrely commented on lib/misc/global.dart
>  class Global {
O `Global` jsme se bavili na callu, tak to do budoucna promysli 😉

2023-06-19 19:06 UTC, merged